package api

import (
	"context"
	"log/slog"
	"net/http"

	"github.com/chrismott/miniclass/internal/api/handlers"
	"github.com/chrismott/miniclass/internal/api/problems"
	"github.com/chrismott/miniclass/internal/auth"
	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humachi"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
)

const apiBasePath = "/api"

// RouterOptions configures the HTTP router independently of process startup.
type RouterOptions struct {
	AllowedOrigins         []string
	Database               handlers.DatabasePinger
	Logger                 *slog.Logger
	TrustedProxyCIDRs      []string
	Version                string
	Identity               auth.AccountResolver
	Claimer                handlers.InvitationClaimer
	Administrators         handlers.AdministratorManager
	InvitationClaimBaseURL string
	SchoolYears            handlers.SchoolYearService
	AuditLog               handlers.AuditLogReader
	Vocabularies           handlers.VocabularyService
	Adults                 handlers.AdultService
	Students               handlers.StudentService
	Households             handlers.HouseholdService
	GuardianRelationships  handlers.GuardianRelationshipService
	Verifier               auth.Verifier
}

// NewRouter builds the complete API router and middleware chain. Routes are
// declared once through Huma so the same definitions produce the runtime
// handlers and the OpenAPI contract.
func NewRouter(options RouterOptions) chi.Router {
	router, _ := newRouter(options)
	return router
}

// NewOpenAPI builds the API declaration and returns its generated OpenAPI
// document for the cmd/openapi generator.
func NewOpenAPI(options RouterOptions) *huma.OpenAPI {
	_, api := newRouter(options)
	return api.OpenAPI()
}

func newRouter(options RouterOptions) (chi.Router, huma.API) {
	router := chi.NewRouter()
	logger := options.Logger
	if logger == nil {
		logger = slog.Default()
	}

	router.Use(
		middleware.RequestID,
		TrustedProxyRealIP(options.TrustedProxyCIDRs...),
		RequestLogger(logger),
		Recoverer(logger),
		cors.Handler(cors.Options{
			AllowedOrigins:   allowedOrigins(options.AllowedOrigins),
			AllowedMethods:   []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
			AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
			AllowCredentials: false,
			MaxAge:           300,
		}),
	)

	router.NotFound(func(w http.ResponseWriter, _ *http.Request) {
		problems.Write(w, problems.New(http.StatusNotFound, problems.RouteNotFound, "route not found"))
	})
	router.MethodNotAllowed(func(w http.ResponseWriter, _ *http.Request) {
		problems.Write(w, problems.New(http.StatusMethodNotAllowed, problems.MethodNotAllowed, "method not allowed"))
	})

	version := options.Version
	if version == "" {
		version = defaultServerVersion
	}
	options.Version = version
	api := humachi.New(router, humaConfig(version))
	api.UseMiddleware(auth.Middleware(options.Verifier, options.Identity, writeAuthError))
	registerOperations(api, options)
	addProblemTypesToContract(api.OpenAPI())
	return router, api
}

func humaConfig(version string) huma.Config {
	config := huma.DefaultConfig("MiniClass API", version)
	// The committed contract is generated by cmd/openapi. Keep the runtime
	// surface limited to the application routes until an explicit docs route is
	// designed.
	config.OpenAPIPath = ""
	config.DocsPath = ""
	config.SchemasPath = ""
	return config
}

func registerOperations(api huma.API, options RouterOptions) {
	registerOperation(api, huma.Operation{
		OperationID: "get-api-root",
		Method:      http.MethodGet,
		Path:        apiBasePath,
		Summary:     "Get API information",
	}, auth.CapabilityAuthenticated, false, apiRoot)
	registerOperation(api, huma.Operation{
		OperationID: "get-api-root-trailing-slash",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/",
		Summary:     "Get API information",
	}, auth.CapabilityAuthenticated, false, apiRoot)

	health := handlers.NewHealthHandler(options.Database, options.Version)
	registerOperation(api, huma.Operation{
		OperationID: "get-health",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/health",
		Summary:     "Check API and database health",
		Errors:      []int{http.StatusServiceUnavailable},
	}, auth.CapabilityPublic, false, health.Handle)

	registerOperation(api, huma.Operation{
		OperationID: "get-me",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/me",
		Summary:     "Get the authenticated principal",
	}, auth.CapabilityAuthenticated, false, (handlers.MeHandler{}).Handle)

	auditLog := handlers.NewAuditLogHandler(options.AuditLog)
	registerOperation(api, huma.Operation{
		OperationID: "get-audit-log",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/audit-log",
		Summary:     "Read the audit log",
		Errors:      []int{http.StatusBadRequest, http.StatusInternalServerError},
	}, auth.CapabilityReadAuditLog, false, auditLog.Handle)

	claim := handlers.NewClaimInvitationHandler(options.Claimer)
	registerOperation(api, huma.Operation{
		OperationID: "post-auth-claim-invitation",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/auth/claim",
		Summary:     "Claim an administrator invitation",
		Errors:      []int{http.StatusBadRequest, http.StatusForbidden},
	}, auth.CapabilityAuthenticated, true, claim.Handle)

	administrators := handlers.NewAdministratorHandler(options.Administrators, options.InvitationClaimBaseURL)
	registerOperation(api, huma.Operation{
		OperationID: "get-administrators", Method: http.MethodGet, Path: apiBasePath + "/administrators",
		Summary: "List organization administrators",
	}, auth.CapabilityManageAdministrators, false, administrators.List)
	registerOperation(api, huma.Operation{
		OperationID: "post-administrator-invitation", Method: http.MethodPost, Path: apiBasePath + "/administrators",
		Summary: "Invite an administrator",
		Errors:  []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageAdministrators, false, administrators.Invite)
	registerOperation(api, huma.Operation{
		OperationID: "patch-administrator-role", Method: http.MethodPatch, Path: apiBasePath + "/administrators/{memberID}",
		Summary: "Change an administrator role",
		Errors:  []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageAdministrators, false, administrators.ChangeRole)
	registerOperation(api, huma.Operation{
		OperationID: "delete-administrator", Method: http.MethodDelete, Path: apiBasePath + "/administrators/{memberID}",
		Summary: "Remove an administrator",
		Errors:  []int{http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageAdministrators, false, administrators.Remove)
	registerOperation(api, huma.Operation{
		OperationID: "post-administrator-invitation-resend", Method: http.MethodPost, Path: apiBasePath + "/administrators/{memberID}/invitation/resend",
		Summary: "Regenerate an administrator invitation",
		Errors:  []int{http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageAdministrators, false, administrators.Resend)
	registerOperation(api, huma.Operation{
		OperationID: "post-administrator-invitation-revoke", Method: http.MethodPost, Path: apiBasePath + "/administrators/{memberID}/invitation/revoke",
		Summary: "Revoke an administrator invitation",
		Errors:  []int{http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageAdministrators, false, administrators.Revoke)

	schoolYears := handlers.NewSchoolYearHandler(options.SchoolYears)
	registerOperation(api, huma.Operation{
		OperationID: "list-school-years",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years",
		Summary:     "List school years",
	}, auth.CapabilityManageSchoolYear, false, schoolYears.List)
	registerOperation(api, huma.Operation{
		OperationID: "create-school-year",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/school-years",
		Summary:     "Create a school year",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageSchoolYear, false, schoolYears.Create)
	registerOperation(api, huma.Operation{
		OperationID: "get-school-year",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years/{schoolYearID}",
		Summary:     "Get a school year",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageSchoolYear, false, schoolYears.Get)
	registerOperation(api, huma.Operation{
		OperationID: "update-school-year",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/school-years/{schoolYearID}",
		Summary:     "Edit or transition a school year",
		Errors:      []int{http.StatusBadRequest, http.StatusNotFound, http.StatusConflict},
	}, auth.CapabilityManageSchoolYear, false, schoolYears.Update)
	registerOperation(api, huma.Operation{
		OperationID: "delete-school-year",
		Method:      http.MethodDelete,
		Path:        apiBasePath + "/school-years/{schoolYearID}",
		Summary:     "Delete a school year",
		Errors:      []int{http.StatusNotFound, http.StatusConflict},
	}, auth.CapabilityManageSchoolYear, false, schoolYears.Delete)

	vocabularies := handlers.NewVocabularyHandler(options.Vocabularies)
	registerOperation(api, huma.Operation{
		OperationID: "list-vocabularies",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/vocabularies",
		Summary:     "List grade and homeroom vocabularies",
	}, auth.CapabilityManageRoster, false, vocabularies.List)
	registerOperation(api, huma.Operation{
		OperationID: "update-vocabulary-settings",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/vocabularies/settings",
		Summary:     "Update the configured homeroom label",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.UpdateSettings)
	registerOperation(api, huma.Operation{
		OperationID: "list-grade-levels",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/grade-levels",
		Summary:     "List grade levels",
	}, auth.CapabilityManageRoster, false, vocabularies.ListGrades)
	registerOperation(api, huma.Operation{
		OperationID: "create-grade-level",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/grade-levels",
		Summary:     "Create a grade level",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.CreateGrade)
	registerOperation(api, huma.Operation{
		OperationID: "reorder-grade-levels",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/grade-levels/reorder",
		Summary:     "Reorder grade levels",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.ReorderGrades)
	registerOperation(api, huma.Operation{
		OperationID: "get-grade-level",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/grade-levels/{gradeLevelID}",
		Summary:     "Get a grade level",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, vocabularies.GetGrade)
	registerOperation(api, huma.Operation{
		OperationID: "update-grade-level",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/grade-levels/{gradeLevelID}",
		Summary:     "Edit or retire a grade level",
		Errors:      []int{http.StatusBadRequest, http.StatusNotFound, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.UpdateGrade)
	registerOperation(api, huma.Operation{
		OperationID: "list-homerooms",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/homerooms",
		Summary:     "List homerooms",
	}, auth.CapabilityManageRoster, false, vocabularies.ListHomerooms)
	registerOperation(api, huma.Operation{
		OperationID: "create-homeroom",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/homerooms",
		Summary:     "Create a homeroom",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.CreateHomeroom)
	registerOperation(api, huma.Operation{
		OperationID: "get-homeroom",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/homerooms/{homeroomID}",
		Summary:     "Get a homeroom",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, vocabularies.GetHomeroom)
	registerOperation(api, huma.Operation{
		OperationID: "update-homeroom",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/homerooms/{homeroomID}",
		Summary:     "Edit or retire a homeroom",
		Errors:      []int{http.StatusBadRequest, http.StatusNotFound, http.StatusConflict},
	}, auth.CapabilityManageRoster, false, vocabularies.UpdateHomeroom)

	adults := handlers.NewAdultHandler(options.Adults)
	registerOperation(api, huma.Operation{
		OperationID: "list-adults",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years/{schoolYearID}/adults",
		Summary:     "List adults in a school year",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, adults.List)
	registerOperation(api, huma.Operation{
		OperationID: "create-adult",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/school-years/{schoolYearID}/adults",
		Summary:     "Create an adult",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, adults.Create)
	registerOperation(api, huma.Operation{
		OperationID: "get-adult",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years/{schoolYearID}/adults/{adultID}",
		Summary:     "Get an adult",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, adults.Get)
	registerOperation(api, huma.Operation{
		OperationID: "update-adult",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/school-years/{schoolYearID}/adults/{adultID}",
		Summary:     "Edit an adult",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, adults.Update)
	registerOperation(api, huma.Operation{
		OperationID: "delete-adult",
		Method:      http.MethodDelete,
		Path:        apiBasePath + "/school-years/{schoolYearID}/adults/{adultID}",
		Summary:     "Soft-delete an adult",
		Errors:      []int{http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, adults.Delete)

	students := handlers.NewStudentHandler(options.Students)
	registerOperation(api, huma.Operation{
		OperationID: "list-students",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years/{schoolYearID}/students",
		Summary:     "List students in a school year",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, students.List)
	registerOperation(api, huma.Operation{
		OperationID: "create-student",
		Method:      http.MethodPost,
		Path:        apiBasePath + "/school-years/{schoolYearID}/students",
		Summary:     "Create a student",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, students.Create)
	registerOperation(api, huma.Operation{
		OperationID: "get-student",
		Method:      http.MethodGet,
		Path:        apiBasePath + "/school-years/{schoolYearID}/students/{studentID}",
		Summary:     "Get a student",
		Errors:      []int{http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, students.Get)
	registerOperation(api, huma.Operation{
		OperationID: "update-student",
		Method:      http.MethodPatch,
		Path:        apiBasePath + "/school-years/{schoolYearID}/students/{studentID}",
		Summary:     "Edit a student",
		Errors:      []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, students.Update)
	registerOperation(api, huma.Operation{
		OperationID: "delete-student",
		Method:      http.MethodDelete,
		Path:        apiBasePath + "/school-years/{schoolYearID}/students/{studentID}",
		Summary:     "Soft-delete a student",
		Errors:      []int{http.StatusConflict, http.StatusNotFound},
	}, auth.CapabilityManageRoster, false, students.Delete)

	households := handlers.NewHouseholdHandler(options.Households)
	registerOperation(api, huma.Operation{OperationID: "list-households", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/households", Summary: "List households in a school year", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.List)
	registerOperation(api, huma.Operation{OperationID: "create-household", Method: http.MethodPost, Path: apiBasePath + "/school-years/{schoolYearID}/households", Summary: "Create a household", Errors: []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.Create)
	registerOperation(api, huma.Operation{OperationID: "get-household", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}", Summary: "Get a household", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.Get)
	registerOperation(api, huma.Operation{OperationID: "update-household", Method: http.MethodPatch, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}", Summary: "Edit a household", Errors: []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.Update)
	registerOperation(api, huma.Operation{OperationID: "delete-household", Method: http.MethodDelete, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}", Summary: "Soft-delete a household", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.Delete)
	registerOperation(api, huma.Operation{OperationID: "list-household-students", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/students", Summary: "List students in a household", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.ListStudents)
	registerOperation(api, huma.Operation{OperationID: "add-household-student", Method: http.MethodPost, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/students", Summary: "Add a student to a household", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.AddStudent)
	registerOperation(api, huma.Operation{OperationID: "remove-household-student", Method: http.MethodDelete, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/students/{studentID}", Summary: "Remove a student from a household", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.DeleteStudent)
	registerOperation(api, huma.Operation{OperationID: "list-household-adults", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/adults", Summary: "List adults in a household", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.ListAdults)
	registerOperation(api, huma.Operation{OperationID: "add-household-adult", Method: http.MethodPost, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/adults", Summary: "Add an adult to a household", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.AddAdult)
	registerOperation(api, huma.Operation{OperationID: "remove-household-adult", Method: http.MethodDelete, Path: apiBasePath + "/school-years/{schoolYearID}/households/{householdID}/adults/{adultID}", Summary: "Remove an adult from a household", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, households.DeleteAdult)

	guardianRelationships := handlers.NewGuardianRelationshipHandler(options.GuardianRelationships)
	registerOperation(api, huma.Operation{OperationID: "list-guardian-relationships", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/guardian-relationships", Summary: "List guardian relationships in a school year", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, guardianRelationships.List)
	registerOperation(api, huma.Operation{OperationID: "create-guardian-relationship", Method: http.MethodPost, Path: apiBasePath + "/school-years/{schoolYearID}/guardian-relationships", Summary: "Create a guardian relationship", Errors: []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, guardianRelationships.Create)
	registerOperation(api, huma.Operation{OperationID: "get-guardian-relationship", Method: http.MethodGet, Path: apiBasePath + "/school-years/{schoolYearID}/guardian-relationships/{relationshipID}", Summary: "Get a guardian relationship", Errors: []int{http.StatusNotFound}}, auth.CapabilityManageRoster, false, guardianRelationships.Get)
	registerOperation(api, huma.Operation{OperationID: "update-guardian-relationship", Method: http.MethodPatch, Path: apiBasePath + "/school-years/{schoolYearID}/guardian-relationships/{relationshipID}", Summary: "Edit a guardian relationship", Errors: []int{http.StatusBadRequest, http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, guardianRelationships.Update)
	registerOperation(api, huma.Operation{OperationID: "delete-guardian-relationship", Method: http.MethodDelete, Path: apiBasePath + "/school-years/{schoolYearID}/guardian-relationships/{relationshipID}", Summary: "Delete a guardian relationship", Errors: []int{http.StatusConflict, http.StatusNotFound}}, auth.CapabilityManageRoster, false, guardianRelationships.Delete)
}

func registerOperation[I, O any](api huma.API, operation huma.Operation, capability auth.Capability, allowUnresolved bool, handler func(context.Context, *I) (*O, error)) {
	if operation.Extensions == nil {
		operation.Extensions = map[string]any{}
	}
	if operation.Metadata == nil {
		operation.Metadata = map[string]any{}
	}
	operation.Extensions[auth.RequiredCapabilityExtension] = string(capability)
	operation.Metadata[auth.RequiredCapabilityExtension] = string(capability)
	if allowUnresolved {
		operation.Extensions[auth.AllowUnresolvedPrincipalExtension] = true
		operation.Metadata[auth.AllowUnresolvedPrincipalExtension] = true
	}
	// A public operation states "no security" explicitly rather than leaving
	// Security nil, which would let it inherit any future document-level
	// default and quietly advertise a token it will never read.
	if capability == auth.CapabilityPublic {
		operation.Security = []map[string][]string{}
	} else {
		operation.Security = []map[string][]string{{"bearerAuth": {}}}
	}
	huma.Register(api, operation, handler)
}

type apiRootOutput struct {
	Body struct {
		Service string `json:"service" doc:"Name of the API service."`
	}
}

func apiRoot(context.Context, *struct{}) (*apiRootOutput, error) {
	response := &apiRootOutput{}
	response.Body.Service = "miniclass-api"
	return response, nil
}

func addProblemTypesToContract(openAPI *huma.OpenAPI) {
	if openAPI.Extensions == nil {
		openAPI.Extensions = map[string]any{}
	}
	definitions := problems.Definitions()
	problemSlugs := make([]string, 0, len(definitions))
	for _, definition := range definitions {
		problemSlugs = append(problemSlugs, string(definition.Slug))
	}
	openAPI.Extensions["x-miniclass-problem-types"] = problemSlugs
	if openAPI.Components != nil {
		if openAPI.Components.SecuritySchemes == nil {
			openAPI.Components.SecuritySchemes = map[string]*huma.SecurityScheme{}
		}
		openAPI.Components.SecuritySchemes["bearerAuth"] = &huma.SecurityScheme{
			Type: "http", Scheme: "bearer", BearerFormat: "JWT", Description: "Verified Supabase or local ES256/RS256 bearer token.",
		}
	}

	if openAPI.Components == nil || openAPI.Components.Schemas == nil {
		return
	}
	schemas := openAPI.Components.Schemas.Map()
	schemas["ProblemType"] = problems.Schema()
	if errorSchema, ok := schemas["ErrorModel"]; ok && errorSchema.Properties != nil {
		errorSchema.Properties["type"] = &huma.Schema{Ref: "#/components/schemas/ProblemType"}
	}
}

func writeAuthError(ctx huma.Context, failure auth.Failure) {
	slug := problems.AuthenticationUnavailable
	switch failure.Code {
	case auth.FailureAuthenticationRequired:
		slug = problems.AuthenticationRequired
	case auth.FailureInvalidToken:
		slug = problems.InvalidToken
	case auth.FailureNoOrganization:
		slug = problems.NoOrganization
	case auth.FailureMultipleOrganizations:
		slug = problems.MultipleOrganizations
	case auth.FailureCapabilityRequired:
		slug = problems.CapabilityRequired
	case auth.FailureMissingCapability:
		slug = problems.CapabilityNotDeclared
	}
	problems.WriteContext(ctx, problems.New(failure.Status, slug, failure.Detail))
}

func allowedOrigins(origins []string) []string {
	if len(origins) == 0 {
		return []string{"*"}
	}
	return origins
}
